	<?php $this->widget('ext.dwz.DwzGridView', array(
		'id'=>'pub-person-grid',
		'dataProvider'=>$model->search(),
		'filter'=>$model,
		//'cssFile'=>'/css/gridview/styles.css',
		'columns'=>array(
			'Id',
		'lD_Number',
		'Name',
		'Sex',
		'Nation',
		'Address',
		/*
		'Country',
		'AllowEdit',
		'AllowDel',
		'SortCode',
		'DeletionFlag',
		'EnabledFlag',
		'CreateOn',
		'CreateBy',
		'CreateUserId',
		'Description',
		*/
			array(
				'class'=>'CButtonColumn',
			),
		),
	)); ?>